services:
  - type: web
    name: neyamot-server
    runtime: docker
    plan: free  # Change to 'starter' or higher for production
    region: oregon  # Choose your preferred region
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # Set this in Render dashboard
      - key: FRONTEND_URL
        sync: false  # Set this in Render dashboard
      - key: JWT_SECRET
        generateValue: true  # Auto-generate secure secret
      - key: PORT
        value: 3000
    healthCheckPath: /api/v1/health
