services:
  - type: web
    name: neyamot-server
    runtime: node
    region: oregon
    plan: free
    buildCommand: pnpm install && npx prisma migrate deploy && pnpm run build
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api
